export const BACKEND_SCHEMA_VERSION = 1;

const now = "2026-07-05T00:00:00.000Z";

export function createSeedDatabase() {
  return {
    meta: {
      schemaVersion: BACKEND_SCHEMA_VERSION,
      createdAt: now,
      updatedAt: now,
    },
    roles: [
      {
        key: "admin",
        name: "GM/Admin Console",
        domain: "admin",
        description: "모든 역할 콘솔을 전환하고 감사 로그와 실행 상태를 확인합니다.",
        permissions: ["roles:read", "cases:read", "cases:write", "agent-runs:write", "audit:read", "files:write"],
      },
      {
        key: "rm-officer",
        name: "RM 업무지원 포털",
        domain: "여신 상담",
        description: "여신 상담 큐, 정책금융 체크리스트, 승인 라우팅을 급한 순 근거 기반으로 지원합니다.",
        permissions: ["cases:read", "cases:write", "agent-runs:write", "deliverables:read", "audit:read", "files:write"],
      },
      {
        key: "jeonse-protection",
        name: "전세사기 보호 업무지원 포털",
        domain: "시세·권리·보증·피해지원",
        description: "전세 위험 신호와 확인 항목만 제안하고, 전세사기 여부와 보증·피해자 결정은 담당자가 판단합니다.",
        permissions: ["cases:read", "cases:write", "agent-runs:write", "deliverables:read", "audit:read", "files:write", "public-data:read"],
      },
      {
        key: "corporate-credit",
        name: "기업여신 업무지원 포털",
        domain: "기업여신 심사",
        description: "재무, 담보, DSCR, 심사 단계 데이터를 기준으로 검토 큐와 에이전트 산출물을 생성합니다.",
        permissions: ["cases:read", "cases:write", "agent-runs:write", "deliverables:read", "audit:read", "files:write"],
      },
      {
        key: "woori-capital",
        name: "JB우리캐피탈 운영 포털",
        domain: "계열사 운영",
        description: "계열사 전용 관리 건, 승인, 감사 기록을 분리된 scope로 운영합니다.",
        permissions: ["cases:read", "cases:write", "agent-runs:write", "deliverables:read", "audit:read", "files:write"],
      },
    ],
    cases: [
      {
        id: "case-rmo-204",
        roleKey: "rm-officer",
        caseNo: "JBG-204",
        title: "완도 양식장 재해위험 대응",
        customerAlias: "CUST-RM-204",
        region: "전남 완도",
        status: "approval_pending",
        riskLevel: "high",
        urgency: "urgent",
        summary: "기상특보와 양식장 시설 피해 우려가 겹쳐 RM 검토와 고객 안내가 필요한 케이스입니다.",
        dataScope: ["상담 메모", "기상특보 샘플", "상환 일정", "담보 정보"],
        nextAction: "재해·해상 리스크 에이전트 실행 후 담당자 승인 기록을 남깁니다.",
        agentQueue: ["rmo-triage", "rmo-marine-risk", "rmo-action"],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "case-jeonse-0004",
        roleKey: "jeonse-protection",
        caseNo: "JEONSE-0004",
        title: "인천 미추홀구 주안동 다가구 위험 점검",
        customerAlias: "CUST-JS-0004",
        region: "인천 미추홀구",
        status: "human_review_required",
        riskLevel: "critical",
        urgency: "auction_urgent",
        summary: "경·공매 통지, 다가구 단독 포함, 보증금 1.2억, 계약만기 2026-06-14 조건으로 권리관계와 피해지원 연결 검토가 필요합니다.",
        dataScope: ["시세 스냅샷", "등기 요약", "보증 신청 메모", "상담 기록"],
        nextAction: "권리관계 확인과 피해지원 신청 요건을 분리해 담당자 검토 큐로 올립니다.",
        agentQueue: ["jpo-orchestrator", "jpo-price-risk", "jpo-title-registry", "jpo-support-guide"],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "case-ccr-1001",
        roleKey: "corporate-credit",
        caseNo: "CCR-1001",
        title: "제조업 운전자금 증액 심사",
        customerAlias: "BIZ-CCR-1001",
        region: "전북 익산",
        status: "in_review",
        riskLevel: "medium",
        urgency: "normal",
        summary: "원재료 단가 상승과 매출채권 회수 지연으로 운전자금 증액 요청이 접수된 기업여신 케이스입니다.",
        dataScope: ["재무제표 요약", "매출채권 aging", "담보 목록", "DSCR 계산표"],
        nextAction: "DSCR와 담보 커버리지 근거를 산출한 뒤 심사자 검토로 넘깁니다.",
        agentQueue: ["ccr-financial-reader", "ccr-dscr-check", "ccr-collateral-review"],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "case-jbwc-104",
        roleKey: "woori-capital",
        caseNo: "JBG-104",
        title: "전주 중앙로 카페 리스 관리 건",
        customerAlias: "CUST-JBWC-104",
        region: "전북 전주",
        status: "approval_pending",
        riskLevel: "medium",
        urgency: "attention",
        summary: "리스료 납입 지연과 고객 안내 이력이 있어 담당자 승인 후 후속 안내가 필요한 관리 건입니다.",
        dataScope: ["리스 계약 요약", "납입 이력", "상담 기록"],
        nextAction: "고객 안내 초안과 담당자 승인 기록을 생성합니다.",
        agentQueue: ["jbwc-triage", "jbwc-guidance"],
        createdAt: now,
        updatedAt: now,
      },
    ],
    agentRuns: [],
    deliverables: [],
    auditLogs: [
      {
        id: "audit-seed-001",
        roleKey: "admin",
        caseId: null,
        actorId: "system",
        action: "BACKEND_SEEDED",
        targetType: "database",
        targetId: "local-json",
        message: "로컬 백엔드 seed 데이터가 생성되었습니다.",
        riskLevel: "low",
        reviewRequired: false,
        createdAt: now,
      },
    ],
    files: [],
    counters: {
      case: 1000,
      run: 1000,
      deliverable: 1000,
      audit: 1000,
      file: 1000,
    },
  };
}
